--liquibase formatted sql

--changeset vova:1
CREATE TABLE notification_tasks
(
    id                     bigint generated by default as identity primary key,
    message                text,
    chat_id                bigint    not null,
    notification_date_time timestamp not null
);

